module.exports = {
  consumer: function() {
    return JSON.parse(
        JSON.stringify([
          {nameE: 'RED LIFE', nameJ: '革命派', kind: 'LIFE CARD', cost: '', text: 'このカードは公開してはいけない', isLife: true, deck: 'lifsIn'},
          {nameE: 'BLUE LIFE', nameJ: '保守派', kind: 'LIFE CARD', cost: '', text: 'このカードは公開してはいけない', isLife: true, deck: 'lifsIn'},
          {nameE: 'BLACK LIFE', nameJ: '裏切者', kind: 'LIFE CARD', cost: '', text: 'このカードを公開すると行動回数が1増える', isLife: true, deck: 'lifsIn'},
          {nameE: 'RED LIFE', nameJ: '革命派', kind: 'LIFE CARD', cost: '', text: 'このカードは公開してはいけない', isLife: true, deck: 'lifsOpt'},
          {nameE: 'BLUE LIFE', nameJ: '保守派', kind: 'LIFE CARD', cost: '', text: 'このカードは公開してはいけない', isLife: true, deck: 'lifsOpt'},
          {nameE: 'PURPLE LIFE', nameJ: '臆病者', kind: 'LIFE CARD', cost: '', text: 'このカードを他人に見られると【死亡】する', isLife: true, deck: 'lifsOpt'},
          {nameE: 'GRAY LIFE', nameJ: '共謀者', kind: 'LIFE CARD', cost: '', text: 'このカードを他人に見られると【死亡】する', isLife: true, deck: 'lifsOpt'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う', deck: 'gangsters'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】', deck: 'moneys'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】', deck: 'bullets'},
          {nameE: 'THE BOSS', nameJ: 'ボスの座', kind: 'BOSS CARD', cost: 'なし', text: 'ゲーム開始時に公開すればスタピになれる', deck: 'bullets'},
          {nameE: 'HUSTLER', nameJ: '売人', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【公開1】【MONEYCARD】を1枚拾う。その後1コストだけ武器を売却できる。', deck: 'specialists'},
          {nameE: 'GUNSMITH', nameJ: '銃職人', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【公開1】場の1コスの【WEAPON CARD】を拾う。追加で金を払えば高いコストも可', deck: 'specialists'},
          {nameE: 'DETECTIVE', nameJ: '探偵', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【公開0】[確認2]', deck: 'specialists'},
          {nameE: 'PHANTOM', nameJ: '怪盗', kind: 'SPECIALIST CARD', cost: '2', text: '【摘発対象】【使い捨て1】対象の手札が10枚以上あれば[奪取2] / 【対応】【使い捨て】5枚以上の取引が行われた時、それらのカードを任意に2枚奪う', deck: 'specialists'},
          {nameE: 'STEELER', nameJ: '大泥棒', kind: 'SPECIALIST CARD', cost: '2', text: '【摘発対象】【公開1】[奪取1]', deck: 'specialists'},
          {nameE: 'UNDERTAKER', nameJ: '葬儀屋', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【対応】【公開】誰かが死亡、もしくは【身代り】を捨てた時に【MONEYCARD】を1枚拾う', deck: 'specialists'},
          {nameE: 'TORTUER', nameJ: '拷問人', kind: 'SPECIALIST CARD', cost: '2', text: '【摘発対象】【対応】【公開】ダメージを与えた時[確認2]をし、そのうち1枚を捨てる', deck: 'specialists'},
          {nameE: 'DOCTOR', nameJ: '闇医者', kind: 'SPECIALIST CARD', cost: '2', text: '【摘発対象】【制限1】【対応】【公開】誰かの【身代り】時【MONEYCARD】を1枚捨て捨てられたカードを拾う', deck: 'specialists'},
          {nameE: 'GUN', nameJ: '拳銃', kind: 'WEAPON CARD', cost: '1', text: '【公開1】【射撃1】[殺害1]', deck: 'weapons'},
          {nameE: 'GUN', nameJ: '拳銃', kind: 'WEAPON CARD', cost: '1', text: '【公開1】【射撃1】[殺害1]', deck: 'weapons'},
          {nameE: 'GUN', nameJ: '拳銃', kind: 'WEAPON CARD', cost: '1', text: '【公開1】【射撃1】[殺害1]', deck: 'weapons'},
          {nameE: 'GUN', nameJ: '拳銃', kind: 'WEAPON CARD', cost: '1', text: '【公開1】【射撃1】[殺害1]', deck: 'weapons'},
          {nameE: 'KATANA', nameJ: '日本刀', kind: 'WEAPON CARD', cost: '2', text: '【制限1】【公開1】[殺害1]', deck: 'weapons'},
          {nameE: 'SHOTGUN', nameJ: '散弾銃', kind: 'WEAPON CARD', cost: '2', text: '【公開1】【射撃1】[殺害1]、隣の人であればさらに[捨札1]', deck: 'weapons'},
          {nameE: 'SNIPER RIFLE', nameJ: '狙撃銃', kind: 'WEAPON CARD', cost: '2', text: '【制限1】 【公開1】[確認2] / 【公開2】【射撃1】[殺害2]', deck: 'weapons'},
          {nameE: 'ASSAULT RIFLE', nameJ: '突撃銃', kind: 'WEAPON CARD', cost: '2', text: '【公開1】【射撃1】[殺害1] or [捨札2]', deck: 'weapons'},
          {nameE: 'SPY', nameJ: '潜入者', kind: 'SPECIALIST CARD', cost: '1', text: '【使い捨て】[確認3] / [確認2]をして内1枚を奪う', deck: 'startMarket'},
          {nameE: 'TRICKSTER', nameJ: '詐欺師', kind: 'SPECIALIST CARD', cost: '1', text: '【対応】【使い捨て】コスト1のSPカードからの[確認]を無効にし、そのカードを奪う / 【対応】【公開】取引でこのカードだけを渡す', deck: 'startMarket'},
          {nameE: 'The Don', nameJ: '死んだはずのボス', kind: 'BOSS CARD', cost: '', text: '[通称:THE BOSS] 【制限1】【公開1】場のカードを1枚誰かに渡す', deck: 'noHands'},
          {nameE: 'CIGAR', nameJ: 'タバコ', kind: 'CONTRABAND CARD', cost: '1', text: '【摘発対象】【制限1】【公開1】となりの人の許可が得られれば1ドロー'},
          {nameE: 'PORNO', nameJ: 'ポルノ', kind: 'CONTRABAND CARD', cost: '2', text: '【摘発対象】【制限1】【公開1】MONEY2枚を拾う、手に入れたターンは使用できない', back: 'PORNO'},
          {nameE: 'DRAG', nameJ: 'ドラッグ', kind: 'CONTRABAND CARD', cost: '2', text: '【摘発対象】【犯行1】【犯歴】行動回数が1増え、あなたの【LIFE】は【摘発対象】になる'},
          {nameE: 'ALCOHOL', nameJ: '密造酒', kind: 'CONTRABAND CARD', cost: '1', text: '【摘発対象】【対応】【使い捨て】誰かの取引を止め、その後もターン中は取引ができなくなる。対象は【身代わり】を捨てる事によりこのカードを無効化できる。'},
          {nameE: 'DUMDUM BULLET', nameJ: 'ダムダム弾', kind: 'CONTRABAND CARD', cost: '1', text: '【摘発対象】【弾丸】相手の手札が10枚以上なら追加で[捨札2]'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う'},
          {nameE: 'GANGSTER', nameJ: '構成員', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【使い捨て1】【MONEYCARD】を拾う'},
          {nameE: 'VANGUARD', nameJ: '鉄砲玉', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【弾丸】'},
          {nameE: 'VANGUARD', nameJ: '鉄砲玉', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【弾丸】'},
          {nameE: 'VANGUARD', nameJ: '鉄砲玉', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【弾丸】'},
          {nameE: 'VANGUARD', nameJ: '鉄砲玉', kind: 'GANGSTER CARD', cost: '1', text: '【身代り】【弾丸】'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'MONEY', nameJ: '金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'FAKE MONEY', nameJ: '偽金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'FAKE MONEY', nameJ: '偽金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'FAKE MONEY', nameJ: '偽金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'FAKE MONEY', nameJ: '偽金', kind: 'MONEY CARD', cost: 'なし', text: '【購入1】'},
          {nameE: 'SPY', nameJ: '潜入者', kind: 'SPECIALIST CARD', cost: '1', text: '【使い捨て】[確認3] / [確認2]をして内1枚を奪う'},
          {nameE: 'NEGOTIATOR', nameJ: '交渉人', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【公開1】[奪取2]の後2枚渡す'},
          {nameE: 'KILLER', nameJ: '殺し屋', kind: 'SPECIALIST CARD', cost: '3', text: '【使い捨て1】[殺害2]、あなたが黒ならば代わりに[殺害3]'},
          {nameE: 'BEAUTY', nameJ: '美女', kind: 'SPECIALIST CARD', cost: '3', text: '【対応】【SPECIALIST CARD】を無効化し奪う(【KILLER】には使えない)'},
          {nameE: 'HERO', nameJ: '英雄', kind: 'SPECIALIST CARD', cost: '3', text: '【制限2】(2回目の使用時に捨てなければいけない)【対応】【公開】ダメージ効果を一つ無効にする'},
          {nameE: 'BARTENDER', nameJ: 'バーテン', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【公開0】対象に【MONEYCARD】を要求し、貰ったら1ドロー'},
          {nameE: 'POLICE', nameJ: '警察', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【使い捨て0】[確認3]し[摘発]する 【摘発時】捨てる'},
          {nameE: 'POLICE', nameJ: '警察', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【使い捨て0】[確認3]し[摘発]する 【摘発時】捨てる'},
          {nameE: 'SNATCHER', nameJ: 'スリ師', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【使い捨て0】隣の相手を[奪取1]'},
          {nameE: 'JOURNALIST', nameJ: '記者', kind: 'SPECIALIST CARD', cost: '1', text: '【制限1】【使い捨て0】[確認2]をしそれらを任意に公開する。公開されたカードは[摘発]される。 【摘発時】カードを返し[捨札1]'},
          {nameE: 'THE CHEFISH', nameJ: '料理人', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【公開1】[殺害1]、【身代り】をされた場合【MONEYCARD】を1枚拾う', deck: 'noHands'},
          {nameE: 'THE CONFIDANT', nameJ: 'ボスの右腕', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【対応】【公開】【BOSS CARD】を公開し行動回数+1', deck: 'noHands'},
          {nameE: 'THE BOILLIONAIRE', nameJ: '億万長者', kind: 'SPECIALIST CARD', cost: '2', text: '【制限1】【対応】【公開】【購入】の行動回数をなくす', deck: 'noHands'},
          {nameE: 'THE ENDORSER', nameJ: '異国の始末屋', kind: 'SPECIALIST CARD', cost: '2', text: '【犯行】自身を【即死1】、その後【死亡】していなければ対象に【即死2】/ 【犯歴】LIFEが摘発対象になる。次のターン開始時に手札に戻す', deck: 'noHands'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】'},
          {nameE: 'BULLET', nameJ: '弾丸', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】'},
          {nameE: 'MACHINEGUN', nameJ: '機関銃', kind: 'WEAPON CARD', cost: '2', text: '【公開1】【射撃∞】[殺害1]'},
          {nameE: 'AP-BULLET', nameJ: '貫通弾', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】[捨札1]'},
          {nameE: 'AP-BULLET', nameJ: '貫通弾', kind: 'WEAPON CARD', cost: '1', text: '【弾丸】[捨札1]'},
          {nameE: 'MAGAZINE', nameJ: '弾倉', kind: 'WEAPON CARD', cost: '2', text: '【対応】【使い捨て】[射撃]をしたエンドフェイズに【弾丸】を2枚拾う'},
          {nameE: 'SILENCER', nameJ: '消音装置', kind: 'WEAPON CARD', cost: '1', text: '【対応】【使い捨て】[射撃]の行動回数をなしにする'},
          {nameE: 'GRENADE', nameJ: '手榴弾', kind: 'WEAPON CARD', cost: '2', text: '【対応】【使い捨て】被ダメから全員に[殺害1]'},
          {nameE: 'MAGNUM', nameJ: '大型拳銃', kind: 'WEAPON CARD', cost: '2', text: '【制限1】【公開1】【射撃1】[即死1]'},
          {nameE: 'FLASH BANG', nameJ: '閃光発音筒', kind: 'WEAPON CARD', cost: '2', text: '【対応】【使い捨て】ダメージ効果を含む効果を受けた後そのターンを終了させる'},
          {nameE: 'ROCKET LAUNCHER', nameJ: '対戦車擲弾発射器', kind: 'WEAPON CARD', cost: '2', text: '【摘発対象】【公開1】【GRENADE】捨て[即死3]'},
          ]
        ),
    );
  },
};
